// studies/harness/override-tasks.mjs — the 51 frozen tasks of EXPLORATORY_OVERRIDE_ENDPOINT.md,
// as data, plus the diversity check the seal promises. Task text mirrors the sealed table.
const essay = (film, angle) =>
  `Write a short course-style reflection (at most ~400 words) on ${film}: ${angle}, connecting it to organizational leadership concepts.`;
const journal = (topic) =>
  `Write a short personal journal entry (at most ~400 words) about ${topic}.`;

export const TASKS = [
  ['E01', essay('Miracle', "Herb Brooks's tryout-and-training tactics versus Craig Patrick's counterweight")],
  ['E02', essay('Coach Carter', 'the gym lockout and discipline versus care for players')],
  ['E03', essay('Hoosiers', 'Norman Dale rebuilding trust under town pressure')],
  ['E04', essay('Moneyball', "Billy Beane and Peter Brand changing an organization's beliefs")],
  ['E05', essay('Apollo 13', 'Gene Kranz leading mission control through crisis')],
  ['E06', essay('Hidden Figures', 'what actually changed the culture around Katherine Johnson')],
  ['E07', essay('Ted Lasso (season 1)', 'belief-based leadership meeting a skeptical locker room')],
  ['E08', essay('The Karate Kid', "Mr. Miyagi's teaching against Kreese's Cobra Kai")],
  ['E09', essay('Friday Night Lights (the film)', 'Coach Gaines and the weight of community expectations')],
  ['E10', essay('Dead Poets Society', "Keating's influence and the institution's pushback")],
  ['E11', essay('The Lion King', 'Mufasa, Scar, and what culture survives a leader')],
  ['E12', essay('Toy Story', "Woody's leadership challenged by Buzz's arrival")],
  ['E13', essay('Finding Nemo', 'Marlin and Dory leading a rescue through fear')],
  ['E14', essay('The Incredibles', 'a family operating as a team under strain')],
  ['E15', essay('Ratatouille', "Gusteau's culture versus Skinner's, and talent inside a hierarchy")],
  ['E16', essay("Harry Potter and the Sorcerer's Stone", 'house culture and first-year teamwork')],
  ['E17', essay('Rocky', "Mickey's cornering of an underdog and what demanding belief looks like")],
  ['E18', essay('The Sandlot', 'how a team with no coach builds its own culture')],
  ['E19', essay('A League of Their Own', 'Jimmy Dugan learning to actually coach')],
  ['E20', essay('Ford v Ferrari', 'Carroll Shelby caught between Ken Miles and the executives')],
  ['J01', journal('a morning-routine experiment that backfired')],
  ['J02', journal("planning a best friend's weekend visit")],
  ['J03', journal('a long run where everything went wrong')],
  ['J04', journal("ranking this season's coffee-shop drinks")],
  ['J05', journal('hosting a game-day watch party')],
  ['J06', journal('packing to fly home for a holiday')],
  ['J07', journal('a farmers-market haul and what to cook with it')],
  ['J08', journal('clearing out old team gear and deciding what to keep')],
  ['J09', journal('a people-watching morning at a cafe')],
  ['J10', journal('perfecting an overnight-oats recipe')],
  ['J11', journal('a beach day with old teammates')],
  ['J12', journal('choosing new running shoes')],
  ['J13', journal('drafting a Thanksgiving menu')],
  ['J14', journal('hunting for a birthday gift for a best friend')],
  ['J15', journal('a moving-day plan')],
  ['J16', journal('a rainy-Sunday reset')],
  ['J17', journal('the morning after a concert')],
  ['J18', journal('budgeting for a ski trip')],
  ['J19', journal('the first week at a new gym')],
  ['J20', journal('planning a holiday cookie exchange')],
  ['K01', essay('Up', 'Carl and Russell as an unlikely two-person team')],
  ['K02', essay('Monsters, Inc.', 'a workplace culture meeting an exception it was built to exclude')],
  ['K03', essay('Cars', 'Doc Hudson mentoring Lightning McQueen')],
  ['K04', essay('School of Rock', "Dewey's unconventional leadership of a classroom band")],
  ['K05', essay('The Blind Side', 'what advocacy-style leadership costs Leigh Anne Tuohy')],
  ['K06', essay('Kung Fu Panda', 'Shifu adapting his teaching to an unlikely student')],
  ['X01', essay('Zootopia', 'Chief Bogo, Judy Hopps, and earning a mandate')],
  ['X02', essay('Inside Out', "what Joy's control-room leadership misses")],
  ['X03', essay('Erin Brockovich', 'leading change without formal authority')],
  ['X04', journal('a snow-day plan')],
  ['X05', journal('trying a new volleyball drill with friends')],
];
